### ISSUE TITLE
addCredentials task deletes all commented out lines

### ISSUE THREAD

**Issue by caseykulm** [etiennestuder/gradle-credentials-plugin#10]
As described in the title when running,

```
$ gradle addCredentials --key MY_KEY --value my_value
```

The updated `$GRADLE_HOME/gradle.encrypted.properties` file is stripped of all commented out lines.

**Comment by caseykulm** [comment]
I'll dig further later if no one else does, but it looks like the issue comes from the java-ordered-properties project here, https://github.com/etiennestuder/java-ordered-properties/blob/master/src/main/java/nu/studer/java/util/OrderedProperties.java#L181

**Comment by caseykulm** [comment]
I will look into it more, but did find this related issue which seems to have to do with the order of loading, setting, and storing. http://stackoverflow.com/questions/18383275/java-properties-store-is-deleting-other-entries

**Comment by caseykulm** [comment]
Seems like it's a known issue that the Java Properties class simply doesn't support retaining comments. People suggest using Apache Common's Configuration API. http://stackoverflow.com/questions/565932/a-better-class-to-update-property-files

**Comment by etiennestuder** [comment]
I do not have the bandwidth to change the current behavior and thus it will not change unless someone provides a PR with test coverage.
