### ISSUE TITLE
Using credentials to authenticate with Gradle plugin repo

### ISSUE THREAD

**Issue by fullben** [etiennestuder/gradle-credentials-plugin#115]
I have the following use case: In order to download Gradle plugins, I need to use a custom repo that requires authentication. Therefore, my `settings.gradle` looks something like this:
```groovy
pluginManagement {
    repositories {
        maven {
            url 'https://my-gradle-plugin-repo-url'
            credentials {
                username 'my-name'
                password 'my-password'
            }
        }
    }
}
...
```
I would like to avoid having to write my password in plaintext in this file. I have seen the example for this project where the credentials plugin is being used in the `settings.gradle` file.

I have tried merging said example with my use case in the following way:
```groovy
pluginManagement {
    plugins {
        id 'nu.studer.credentials' version '3.0'
    }
    repositories {
        maven {
             url 'https://my-gradle-plugin-repo-url'
            credentials {
                username 'my-name'
                password credentials.forKey('my-name')
            }
        }
    }
}
...
```
But this results in a compile time error. I'm assuming this is due to the plugin not being available yet, even if it has been downloaded already:
```
org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method forKey() for arguments ['my-name'] on Credentials [username: my-name] of type org.gradle.internal.credentials.DefaultPasswordCredentials_Decorated.
```
Am I missing something really obvious here or is this kind of a chicken-or-egg problem?

**Comment by etiennestuder** [comment]
> Am I missing something really obvious here or is this kind of a chicken-or-egg problem?

Your latter assessment is correct. Without the plugin downloaded/applied, you cannot configure credentials to be used to download plugins.

**Comment by fullben** [comment]
Makes sense. I really was hoping I was wrong somehow. Guess I'll have to look for a different approach for hiding my credentials then... but thx anyways!

**Comment by AmbroiseS** [comment]
For other people stuck in this situation : 

1. Comment private dependencies in your gradle file or maven 
2. Gradle sync
3. Run task addCredentials with your credentials
4. Comment out and sync
