### ISSUE TITLE
Passing value through console input

### ISSUE THREAD

**Issue by BartDubois** [etiennestuder/gradle-credentials-plugin#120]
Is it possible to enter the value on addCredential task from terminal so it will be not entered to command line and will not be stored in history?

For instance it could looks like this.

```
$ gradle addCredentials --key password
Provide value: *****
```

Where the `*` is what we type into console. Of corse we do not need to display any characters but just read the terminal input.

**Comment by etiennestuder** [comment]
This is currently not supported (and I will not have time to support).

Maybe you find some inspiration for safe passing of credentials here?
https://www.netmeister.org/blog/passing-passwords.html
