### ISSUE TITLE
Decrypt values from Java Side

### ISSUE THREAD

**Issue by Jodge** [etiennestuder/gradle-credentials-plugin#13]
To get the original/decrypted value **gradle.encrypted.properties** all we have to do is to print it from the **build.gradle** **credentials.someKeyValue**

How can we handle a scenario where I want to decrypt/get the original value on the Java side i.e. inside a Java file

**Comment by sustacek** [comment]
Where is your Java file? You can read the value from within Gradle build. You your Gradle is building a Java application or library, it will not have visibility of your Gradle.

You could pass the value from Gradle to Java, for example as a System property (when running the Java class from Gradle). Or you could write a file into src/main/resources, putting the value there during the Gradle build. Then the Java files compiled from in src/main/java would have the value accessible, by reading the file as a resource from classpath.

**Comment by Jodge** [comment]
Thanks a lot, the latter which involves writitng a file into src/main/resource is a suitable option for me.

**Comment by calvertdw** [comment]
One option could be to depend on this plugin in your dependencies, then use the same API the gradle task uses. I'll see if I can get that to work.

**Comment by calvertdw** [comment]
Got it working. Here's the kotlin code for that:
```
fun loadEncryptedCredentials(): HashMap<String, String>
{
    val passphrase = CredentialsPlugin.DEFAULT_PASSPHRASE;
    val credentialsFileName = "gradle.encrypted.properties"
    val credentialsEncryptor = CredentialsEncryptor.withPassphrase(passphrase.toCharArray())
    val credentialsFile = Paths.get(System.getProperty("user.home"), ".gradle", credentialsFileName).toFile()
    val credentialsPersistenceManager = CredentialsPersistenceManager(credentialsFile)
    val decryptedProperties = hashMapOf<String, String>()
    val credentials = credentialsPersistenceManager.readCredentials()
    for (name in credentials.stringPropertyNames())
    {
        decryptedProperties.put(name, credentialsEncryptor.decrypt(credentials.getProperty(name)))
    }
    return decryptedProperties
}

main
{
   val credentials = loadEncryptedCredentials()
   credentials.get("someProperty")
}
```

**Comment by calvertdw** [comment]
It's actually unfortunate to have to depend on `gradleApi()` for this. I'm gonna look into removing that dependency in a fork or a new class.

**Comment by calvertdw** [comment]
It would be great to have one location for secure login info accessible from both Gradle and JVM.

**Comment by etiennestuder** [comment]
The proper solution would be to extract the decryption/encryption logic into its own library and use it both from the plugin and from a user's Java code. But, this is beyond the time I have available to work on this plugin. Thus, unless someone provides a full PR with solid test coverage this will not be implemented. Closing.
