### ISSUE TITLE
Suggestions for default values ​​for credentialsLocation

### ISSUE THREAD

**Issue by xungwoo** [etiennestuder/gradle-credentials-plugin#130]
Thank you so much for providing a nice plugin for managing passwords in a local development environment.

I would like to suggest one change regarding the default value of credentials location.
Entering the password every time with the -PcredentialsPassPhrase option during gradle build is still burdensome and cumbersome.
After all, I think many users will create gradle.encrypted.properties and use the values ​​in that file.
However, the current default value of credentialsLocation is GRADLE_USER_HOME, which is inconvenient to apply to many projects.

I think it is useful to change gradle.encrypted.properties to gradle rootProject directory instead of GRADLE_USER_HOME.
If you are concerned about the side effect of changing the default value, it would be nice to be able to specify it in build.gradle instead of the -P option.

**Comment by xungwoo** [comment]
(answering one's own question)
I figured it out after looking at the code. I can use extra properties to set credentials Location

**Comment by etiennestuder** [comment]
Thanks for the feedback.

> Entering the password every time with the -PcredentialsPassPhrase option during gradle build is still burdensome and cumbersome.

You could create an alias for `./gradlew -PcredentialsPassPhrase=foobar -PcredentialsLocation=./gradle.encrypted.properties`.

> I think it is useful to change gradle.encrypted.properties to gradle rootProject directory instead of GRADLE_USER_HOME.

I don't think it would be a good idea to store credentials (even if encrypted) in the repo itself. 

> If you are concerned about the side effect of changing the default value, it would be nice to be able to specify it in build.gradle instead of the -P option.

You can only specify a custom location via `-PcredentialsLocation`. Specifying the location in the build itself would be too late.
