### ISSUE TITLE
Throw exception for missing properties

### ISSUE THREAD

**Issue by saadfarooq** [etiennestuder/gradle-credentials-plugin#15]
The plugin's behavior for missing properties right now is to just return a null value and let the build system figure it out. However, in a common use case, i.e. supplying credentials to something like maven. It results in the following error.

    > Could not resolve com.example:dep:1.0.
        Required by:
            MyApp:unspecified
         > Could not resolve com.example:dep:1.0.
            > Could not get resource 'https://mvn.mycompany.com/repository/com/example/dep-1.0.pom'.
               > java.lang.NullPointerException (no error message)

It would be a much more useful error if it said something like.
    
    A problem occurred evaluating root project 'example'.
    > Property someAccountUsername should not be null. Have you added it using the credentials task (gradle addCredentials --key someKey --value someValue) ?

The only change required is in CredentialsContainer to throw an exception instead of returning null. What are your thoughts on this?

**Comment by etiennestuder** [comment]
Returning null allows the caller to decide how to deal with the absence of the property in a more sequential way than throwing an exception which forces the user to deal via control flow. Also, I don't requesting a property that does not exist as necessarily being an exceptional/error situation.

I'd like to keep up the current behavior. Closing.
