### ISSUE TITLE
Text containing the dollar symbol ($) will not be en/decrypted properly

### ISSUE THREAD

**Issue by christophpickl** [etiennestuder/gradle-credentials-plugin#18]
seems as the plugin is not capable of encrypting text values containing the dollar symbol ($). the text "somehow" get's cut off. try to encrypt and decrypt a string like `12$34$56$78` and you will see the wrong output.

WORKAROUND: had to change the password of the deployment user in order to get the encryption thing working on the build server...

**Comment by etiennestuder** [comment]
Hi @christophpickl I will take a look. But, it will take me a moment until I get to it.

**Comment by christophpickl** [comment]
thanks @etiennestuder for the quick reply. i've created a sample repository [1] where i've reproduced the bug. if you can pinpoint me where to look, i might try to fix it on my own :)

[1] https://github.com/christophpickl/gradle-credentials-plugin-dollar-bug

**Comment by etiennestuder** [comment]
Thanks for the reproducible case! Honestly, nothing rings an immediate bell to give you a direct pointer where to look. I suggest you try to add a test case to the project to expose the problem. See existing test cases here: https://github.com/etiennestuder/gradle-credentials-plugin/tree/master/src/test/groovy/nu/studer/gradle

**Comment by etiennestuder** [comment]
I took a look. It's a bash thing. The Java process never even gets anything beyond the left side of the $. See it for yourself by running `echo before$after`.

The fix is that you need to escape the $, i.e. `gradle addCredentials --key dollarKey --value before\$after`.

Closing.

**Comment by christophpickl** [comment]
oh right, that makes perfectly sense. thanks for having a deeper look at it 👍
