### ISSUE TITLE
Add support for prefix

### ISSUE THREAD

**Issue by asarkar** [etiennestuder/gradle-credentials-plugin#19]
It is very desirable to have the support for qualified keys. For example, we use this for Maven publication, and the repository credentials change. In the Maven world, credentials are grouped by a unique ID; it'd be useful to have the same feature such that we can do the following.
```
repo1.username=
repo2.username=
```

My suggestion is to add a `--prefix` option to the `addCredentials` task.

**Comment by etiennestuder** [comment]
Why not pass the prefix as part of the key, i.e. `--key=repo1.username` ?

**Comment by etiennestuder** [comment]
Thanks for the request, but I don't see the value in this. Closing.
