### ISSUE TITLE
Credentials are not saved with Java 9

### ISSUE THREAD

**Issue by devedave** [etiennestuder/gradle-credentials-plugin#20]
By using java 9 the file will be created but the credentials are not saved. The file is emtpy. When I'm using an older java version everything is fine.

**Comment by konraifen88** [comment]
Same here for Java 10.
The build finishes with 'successfull' message. Which is misleading in the case that the value is not written. 

Maybe load the value after writing and compare with the input to prevent such a case.

**Comment by etiennestuder** [comment]
@devedave @konraifen88 

- Is this still an issue?
- Is this still an issue with the latest version of the plugin 1.0.5?
- Can you help with the investigation and 
  - run the functional tests of this plugin and check if they pass when using Java 9?
  - check if [java-ordered-properties](https://github.com/etiennestuder/java-ordered-properties) test succeed with Java 9?

**Comment by etiennestuder** [comment]
I tracked down the issue to the OrderedProperties class and released a new version 1.0.2 of the java-ordered-properties binary. I then updated the gradle-credentials-plugin to make use of the new binary and released version 1.0.6 of the plugin.
