### ISSUE TITLE
Inconsistent property scope of credentialsPassphrase

### ISSUE THREAD

**Issue by sboardwell** [etiennestuder/gradle-credentials-plugin#21]
Hi Etienne, 

I can add credentials with 
    `./gradlew addCredentials .... -PcredentialsPassphrase=xyz`
remove also works. 

However, to use the credentials I need to set the JVM property with `-D` as in 
    `./gradlew myTask -DcredentialsPassphrase=xyz...` 
instead of the project property.

Is this expected or do I have a problem in my build.gradle?

**Comment by etiennestuder** [comment]
@sboardwell Yes, there must be something else going on. Access always happens via project property in the credentials plugin code.

**Comment by sboardwell** [comment]
Ok, thanks.
