### ISSUE TITLE
gradle kotlin extension support

### ISSUE THREAD

**Issue by dkulig** [etiennestuder/gradle-credentials-plugin#23]
Hey, does credentials plugin support Gradle Kotlin extension (kts) ? If so, how can I get credentials?

**Comment by etiennestuder** [comment]
I don't know. I have not looked into this, and I will not have time anytime soon.

**Comment by dkulig** [comment]
I can confirm, it does work.

```
val credentials: CredentialsContainer by project.extra
val username = credentials.getProperty("username") as String
val password = credentials.getProperty("password") as String
```

**Comment by antonbezpalov** [comment]
Hi @dkulig, could you please provide your full example? When I try your solution I see an error: `Unresolved reference: CredentialsContainer`

**Comment by rburgst** [comment]
@antonbezpalov you probably need 
```
import nu.studer.gradle.credentials.domain.CredentialsContainer
```
at the top of your file

**Comment by rburgst** [comment]
@etiennestuder it would be nice to include this info in the README

**Comment by etiennestuder** [comment]
@rburgst not sure how to make it more obvious:
https://github.com/etiennestuder/gradle-credentials-plugin/blob/master/README.md#apply-credentials-plugin

**Comment by rburgst** [comment]
this does not explain how to use it concretely in a kotlin script gradle file.

IMHO a code block such as 

```
import nu.studer.gradle.credentials.domain.CredentialsContainer

plugins {
    id("nu.studer.credentials") version "2.1"
}

val credentials: CredentialsContainer by project.extra
val username = credentials.getProperty("username") as String
val password = credentials.getProperty("password") as String
```

would have helped quite a bit.

**Comment by arakn3t** [comment]
@timkabot to use version 3.0 replace .getProperty with .forKey

`import nu.studer.gradle.credentials.domain.CredentialsContainer

plugins {
    id("nu.studer.credentials") version "3.0"
}

val credentials: CredentialsContainer by project.extra
val username = credentials.forKey("username") as String
val password = credentials.forKey("password") as String`
