### ISSUE TITLE
Allow specifying file location

### ISSUE THREAD

**Issue by snowe2010** [etiennestuder/gradle-credentials-plugin#26]
It is currently impossible to use the credentials plugin in jenkins with the Config File Provider Plugin. This is due to the way that the Config File Provider Plugin randomizes the file names to avoid conflicts with other things on the system.

**Comment by etiennestuder** [comment]
If you provide a PR with a solid implementation and test coverage, I'm happy to integrate it.

**Comment by etiennestuder** [comment]
The location of the directory in which the credentials file is stored is configurable in version 1.0.7.

**Comment by snowe2010** [comment]
oh thanks! Sorry I didn't get back to you on this. Forgot about it while I was in a rush to finish other things.
