### ISSUE TITLE
More documentation on credentials location and passphrase

### ISSUE THREAD

**Issue by Kobatsu** [etiennestuder/gradle-credentials-plugin#28]
Hello,
This plugin seems great, however I am not really comfortable with gradle and couldn't make it work.
I am not sure that the credentials are loaded from the good file location and I don't know how to do it properly.
Can you give more examples on how to do it?

I did this :
`gradlew addCredentials --key username--value MyUsername -PcredentialsLocation="."`
`gradlew addCredentials --key password --value MyPassword -PcredentialsLocation="."`

I need these plugins in the credentials to connect to my maven repository where I have this :

    `maven {
        url 'MyMavenUrl'
        println 'user / password :' + credentials.username + '/' + credentials.password

        credentials {
            username credentials.username
            password credentials.password
        }
    }`

The println displays :
user / password :null/null

I don't know how to set the project property credentialsLocation and how to check its value at runtime.

I think I am not alone since I found this [StackOverflow post](https://stackoverflow.com/questions/55347492/how-to-access-encrypted-passwords-from-specific-location-using-gradle-credential)

**Comment by etiennestuder** [comment]
@Kobatsu See [this issue](https://github.com/etiennestuder/gradle-credentials-plugin/issues/16) and how to deal with it.
