### ISSUE TITLE
Support for SapMachine 11

### ISSUE THREAD

**Issue by andreas-becker** [etiennestuder/gradle-credentials-plugin#29]
Hello Etienne,
we develop Hybris with SapMachine 11.
On a new setup the credentials file is not created.
As a temporay fix we have to switch to an older java version to create the file.

Maybe you could extend your plugin to support SapMachine 11?

Kind regards,
Andreas

--
Gradle 5.4.1
SAP SE 11.0.4+11-LTS-sapmachine
Windows 10 amd64

**Comment by etiennestuder** [comment]
@andreas-becker I have no plans to support SapMachine 11.
