### ISSUE TITLE
Provide a way to specify credentials interactively without echo

### ISSUE THREAD

**Issue by ddimtirov** [etiennestuder/gradle-credentials-plugin#31]
On Windows there is no equivalent of `read -s` and done has to resort to advanced trickery if they want to avoid reviewing their password on the screen and in the `clink` history.

Would be nice if we could say `addCredentials --interactive` and be prompted for inputs on the console. The password should be read without echo, though echoing stars may be good for usability.

**Comment by etiennestuder** [comment]
To make this work reliably, Gradle itself needs to first support
interactivity, also when running with a daemon.

**Comment by chhex** [comment]
Not knowing how feasible this is, it would be great to have the option for an interactive client for the gradle daemon

**Comment by etiennestuder** [comment]
I'll close this issue. It can be reopened once there is proper support in Gradle.

**Comment by ddimtirov** [comment]
Not sure if this counts as "proper support", but the Gradle documentation is using the `Console` API in example reading GPG passphrase.

https://docs.gradle.org/current/userguide/signing_plugin.html#sec:signatory_credentials

**Comment by etiennestuder** [comment]
@ddimtirov Want to give it a stab and provide a PR with an interactive mode (--interactive) that reads the credentials from the Console, working in both daemon and non-dameon mode, or at least failing gracefully in case of daemon mode?

**Comment by ddimtirov** [comment]
Let's see if I can clear it with my company legal first...

**Comment by etiennestuder** [comment]
I will close this issue. We can reopen it once it gets some traction.
