### ISSUE TITLE
[feature] Hidden prompt for value

### ISSUE THREAD

**Issue by jeremy-coulon** [etiennestuder/gradle-credentials-plugin#32]
I don't really like to type my password in plain text like:
`./gradlew addCredentials --key password --value mypassword`
I hate when someone is looking over my shoulder and I have to type a password.

It would be better if addCredentials could prompt for hidden value instead:
```
./gradlew addCredentials --key password
******
```

**Comment by etiennestuder** [comment]
As I had already replied on various raised issues, interactive mode is not supported in Gradle when using the daemon. Until this is available in Gradle, this functionality will not be available in this plugin.
