### ISSUE TITLE
Plugin repositories in settings.gradle

### ISSUE THREAD

**Issue by darlaam** [etiennestuder/gradle-credentials-plugin#33]
Seems that PR #27 intends to allow the use of the plugin in settings.gradle, with the idea to be able to use credentials for custom plugin repositories.  
I can't find how to do this. Could you document it ?

**Comment by etiennestuder** [comment]
This is what I have: https://github.com/etiennestuder/gradle-credentials-plugin/tree/master/example/settings_application

**Comment by etiennestuder** [comment]
Whether it works for your use case, I cannot tell for sure. If it works, great. If not, there is nothing I can do about it due to limited available time.

**Comment by etiennestuder** [comment]
Let me know how it goes :-)

**Comment by darlaam** [comment]
I'd seen the examples. I hoped that it was possible to do something like for the plugin repository : 
```
repositories {
   url https://my/repo
   credentials {
      username user
      password pwd
  }
}
```
where pwd is taken from the credentials plugin, as we do it in *build.gradle*.
  
But seems that we can't do it, too bad. :disappointed: 
Thanks for your quick answer !

**Comment by etiennestuder** [comment]
In order to use the credentials plugin you need to make it part of the Gradle build and for that you need to specify the plugins block, and thus in there you cannot yet use the credentials DSL. It's not per-se an issue of this plugin.
