### ISSUE TITLE
How to read the credentials from a custom location?

### ISSUE THREAD

**Issue by felipeafonsosantiago** [etiennestuder/gradle-credentials-plugin#35]
I have success in setting the custom `credentialsLocation`, the file was created exactly where set, but I can't read the file now. I've read the documentations and I am not sure if I also have to set the `credentialsLocation` when reading and, if so, where and how to use it.

**Comment by etiennestuder** [comment]
Yes, you also need to pass the project property when reading credentials. See this func test:
https://github.com/etiennestuder/gradle-credentials-plugin/blob/master/src/test/groovy/nu/studer/gradle/credentials/CredentialsFuncTest.groovy#L120
