### ISSUE TITLE
Usage in CI (Jenkins)

### ISSUE THREAD

**Issue by sebersole** [etiennestuder/gradle-credentials-plugin#36]
The plugin has really helped.  Thanks Eitenne!

Any pointers for usage of this plugin for security when building in a CI (Jenkins, specifically) environment?

**Comment by etiennestuder** [comment]
Hi Steve, glad to hear it helps :-)

I have not made use of the credentials functionality on CI, and instead passed in credentials via environment variables on CI. 

See this build script for an example:
https://github.com/etiennestuder/teamcity-build-scan-plugin/blob/20740652fb766714ef9eedd67837e2c10886b4df/build.gradle#L93

I'm not an expert on Jenkins (we use TeamCity), and I just know that there are various Jenkins plugins that allow you to store credentials in a internal/external credentials store and make them available at build execution time via variables. That seems the preferred way to me for CI.

**Comment by sebersole** [comment]
You mean to have a "cascade" of checks?  Like:

```
String username;
String password;
if ( jenkinsDefinedSetting() ) {
    username = usernameFromJenkins();
    password = passwordFromJenkins();
}
else {
    username = usernameFromPlugin();
    password = passwordFromPlugin();
}
```

I could leverage `-PcredentialsLocation` to point to a predefined `gradle.encrypted.properties` file as an alternative?  Which could easily come from a Jenkins variable.

**Comment by etiennestuder** [comment]
Yes, in my case, the cascade is like this: `user = credentials.BINTRAY_USER ?: System.getenv('BINTRAY_USER')`. I first check on the credentials object whether a given key is available and if not, I fall back to an env variable.

> I could leverage -PcredentialsLocation to point to a predefined gradle.encrypted.properties file as an alternative? Which could easily come from a Jenkins variable.

Absolutely.

**Comment by sebersole** [comment]
> credentials.BINTRAY_USER

Not anymore ;)

Anyway, thanks!  That definitely helps

**Comment by etiennestuder** [comment]
> Not anymore ;)

Very true! :-|

Adjusting all my plugins' builds is still on my list.
