### ISSUE TITLE
Incompatible with Gradle 7

### ISSUE THREAD

**Issue by mversaggi** [etiennestuder/gradle-credentials-plugin#39]
When attempting to execute task `removeCredentials` on a known and existing key, I came across the following error:

> Minimal config installed for [removeCredentials]
> Task :removeCredentials FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem was found with the configuration of task ':removeCredentials' (type 'RemoveCredentialsTask').
>   - In plugin 'nu.studer.credentials' type 'nu.studer.gradle.credentials.RemoveCredentialsTask' property 'credentialsKey' is missing an input or output annotation.
> 
>     Reason: A property without annotation isn't considered during up-to-date checking.
> 
>     Possible solutions:
>       1. Add an input or output annotation.
>       2. Mark it as @Internal.
> 
>     Please refer to https://docs.gradle.org/7.1.1/userguide/validation_problems.html#missing_annotation for more details about this problem.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 3s

The Gradle wrapper version we're using for our project is 7.1.1, however I was able to verify that reverting to 6.9 does in fact fix the error above. 

While only one property is explicitly stated as missing an annotation here, I assumed it would be helpful to have an all-encompassing issue to address Gradle 7 compatibility in case there are other minor updates needed. Certainly feel free to edit this issue if more specificity would be preferred.

Happy to provide any additional information if helpful!

**Comment by etiennestuder** [comment]
Thanks for the report. This was already fixed on master, but not yet released. I did a 2.2 release today.

**Comment by mversaggi** [comment]
Thank you!
