### ISSUE TITLE
Can't set credentialsLocation in build or settings files

### ISSUE THREAD

**Issue by Aemerson3418** [etiennestuder/gradle-credentials-plugin#41]
Gradle: 7.2
Credentials Plugin: 3.0
Java: Open JDK 14
IntelliJ: 2021.2.1

I would like to store the encrypted properties file in version control with my project. When adding the credentials I was able to set the -PcredentialsLocation flag to the root project directory, but I cannot seem to set it inside the settings.gradle or build.gradle files.

Things I have attempted in both files:
credentialsLocation = System.getProperty('user.dir')
project.credentialsLocation = System.getProperty('user.dir')
rootProject.credentialsLocation = System.getProperty('user.dir')

In all cases the build fails with "groovy.lang.MissingPropertyException: Could not set unknown property 'credentialsLocation'". To be honest I am not sure if this is a bug or something I am doing wrong. If it is something I am doing wrong please just let me know and perhaps update the readMe to better document the correct process.

**Comment by etiennestuder** [comment]
Try adding it to the `gradle.properties` file located in the root of your project.

```
credentialsLocation=my/path/...
```

**Comment by Aemerson3418** [comment]
And now I feel really dumb. That worked thanks!

**Comment by etiennestuder** [comment]
> And now I feel really dumb. 

Don't :-)
