### ISSUE TITLE
Support for gradle versions < 5

### ISSUE THREAD

**Issue by f3rdy** [etiennestuder/gradle-credentials-plugin#42]
For very odd reasons I need to provide credential plaintext hiding on a gradle 2.13 based project. Using this cool plugin in other projects successfully, I'm now forced to find a different solution, because of:

```bash
* What went wrong:
A problem occurred evaluating root project 'myproject'.
> Failed to apply plugin [id 'nu.studer.credentials']
   > This version of the credentials plugin is not compatible with Gradle < 5.0
```

Are there any suggestions on what to do/use apart from "upgrade your project to use a newer gradle version"?

**Comment by etiennestuder** [comment]
Besides upgrading, you could clone this project and adjust the plugin such that it works with Gradle 2.x.
