### ISSUE TITLE
How to set credentialsPassphrase for build.gradle

### ISSUE THREAD

**Issue by skauss** [etiennestuder/gradle-credentials-plugin#49]
Hi
I try to get an encrypted value from credentials plugin.
To do this I add an secret value with 

gradlew addCredentials --key keyPassword --value 'asdf@|!sdf -PcredentialsPassphrase='my_pass_redentials'

The entry is file ~/.gradle/gradle.E6EDACFABAB055B8D9EEC4D4E33EF714.encrypted.properties

To get it back in my build.gradle file I use

String password = credentials.forKey('keyPassword')
and get "null"

If I add keyPassword without credentialsPassphrase it work well.

How to configure the plugin to read the credentialsPassphrase from a file or environment ?
I read this 
`If a custom passphrase is passed through the credentialsPassphrase project property when starting the build, the credentials container is initialized with all credentials persisted in the passphrase-specific GRADLE_USER_HOME/gradle.MD5HASH.encrypted.properties where the MD5HASH is calculated from the specified passphrase.`

But the big question where to set it ?
The build.gradle build run inside an Jenkins instance.

Next question in the same direction.
How to work with multiple project's on my build machine ?
I like use some think 

project1.credentialsPassphrase='my_pass_redentials'
project2.credentialsPassphrase='my_pass_redentialsXXXX'

Is this possible ?
I didn't like to store credentialsPassphrase inside an build.gradle file which life in git.

Regards
Stephan

**Comment by etiennestuder** [comment]
If you use a passphrase to store credentials, you also need to use the passphrae when you read the credentials. Of course, you would not set the passphrase in the build.gradle itself but pass it from the outside.
