### ISSUE TITLE
Interactive mode

### ISSUE THREAD

**Issue by astellingwerf** [etiennestuder/gradle-credentials-plugin#5]
It'd be great if the plugin would allow for an interactive mode to enter the credentials. Now the password needs to be a plain text command line argument. It is thereby stored in command line history. I'd hope you could invoke the addCredentials task with a key only, where the command line would prompt for the password.

**Comment by sustacek** [comment]
I was wondering about the same. I found following workaround, basically adding the 'ask' part as separate task invoked before 'addCredentials' if needed:

```
apply plugin: nu.studer.gradle.credentials.CredentialsPlugin

task askForCredentialValue {
    group 'Credentials'
    description 'Used to read the value for a credential key from STDIN if --value is not provided. ' +
                    'Value will then not be stored in e.g. Bash history.'

    onlyIf {
        // only ask for the value if it was not provided, with e.g. '--value' on command line
        !addCredentials.credentialsValue
    }

    doLast {
        // based on: https://mrhaki.blogspot.cz/2010/09/gradle-goodness-get-user-input-values.html
        
        def console = System.console()

        if (console) {
            println "> ### Please enter your secret value for key " +
                    "'${addCredentials.credentialsKey}' and hit ENTER: ###"

            def password = console.readPassword()

            // 'credentialsValue' is a project property read by 'addCredentials' task
            // in execution phase, by default based on --value command line argument
            project.ext.credentialsValue = password.toString()
        } else {
            throw new GradleException(
                    "Cannot get console (to read from STDIN), are you using Gradle daemon? " +
                    "Make sure to use --no-daemon (or equivalent setting) - we need " +
                    "Gradle to be interactive in order to read secret value from STDIN.")
        }
    }
}

addCredentials {
    dependsOn askForCredentialValue

    doLast {
        if (it.state.failure == null) {
            println "Successfully added encrypted value for key '${credentialsKey}' into credentials store"
        }
    }
}
```

Please note I've added this code into init.gradle (to not force users to use credentials store if they do not want to. Jenkins has its own way of encrypting secretes and can provide them to the build). So the actual code in build.gradle might be slightly different. I've tried this with Gradle 3.5 only (so far), through wrapper.

I'd love to have `askForCredentialValue` added into the plugin itself. Passing --value (or even the passphase for the store) on command line is indeed not optimal.

**Comment by etiennestuder** [comment]
Thanks, I will take a look. But it will take some time given my current work load in my professional life.

**Comment by RobertKielty** [comment]
I'm looking at using this plugin and I had a similar concern regarding the placement of any credential on the command line owing to it being captured in a history file in bash.

It may be useful for passers-by to note that it is possible to control the bash HISTORY feature to exclude sensitive data using the `HISTIGNORE` environment variable.

So if you ensure to have the following executed prior to seeing your bash prompt, placing a space at the start of your command will exclude the placement of that command into the history file.

It should also exclude commands that include the patterns,  **password** in any combination of case (The & excludes duplicate lines from the history file.)

`HISTIGNORE="&:[ \t]*:*[Pp][Aa][Ss][Ss][Ww][Oo][Rr][Dd]*"`

**Comment by etiennestuder** [comment]
@RobertKielty Thanks for sharing. I like this approach/workaround (however one sees it).

**Comment by etiennestuder** [comment]
@astellingwerf I gave it a try but did not end up with a satisfying outcome. I'd like to wait until Gradle provides some public API to accept user input via console. Until then, I'd say the hint from @RobertKielty might be a feasible workaround. Closing this issue for now.
