### ISSUE TITLE
getCredentialsValue() is an @Input

### ISSUE THREAD

**Issue by astellingwerf** [etiennestuder/gradle-credentials-plugin#7]
`public String getCredentialsValue()` is annotated with `@Input`. This causes the secret value to be stored in plain-text inside `.gradle/2.4/taskArtifacts/taskArtifacts.bin`.

**Comment by etiennestuder** [comment]
Thanks for the report. Fixed in the released version 1.0.2.

**Comment by cmuchinsky** [comment]
I believe the fix for this change might have caused a regression with the `addCredentials` task, it only seems to work once, unless you force it to run again with the `--rerun-tasks` arg. I observed this behavior with Gradle 3.1.

**Comment by etiennestuder** [comment]
Thanks for reporting this. I will investigate.

**Comment by etiennestuder** [comment]
@cmuchinsky As a workaround for now, you can set the task to never be uptodate:
https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/TaskOutputs.html#upToDateWhen(groovy.lang.Closure)

**Comment by etiennestuder** [comment]
@cmuchinsky This is fixed in the latest release [1.0.3](https://github.com/etiennestuder/gradle-credentials-plugin/releases/tag/v1.0.3).
