### ISSUE TITLE
Support properties in gradle.properties in the project directory rather than in the user's home directory

### ISSUE THREAD

**Issue by RemonSinnema** [etiennestuder/gradle-credentials-plugin#9]
The user directory is not always available. One example is when using a SaaS build service like Travis. Another is on an in-house build server that is not accessible to the developer.

**Comment by etiennestuder** [comment]
Though that would be a nice feature to have, I do not have the time to do it. I'm happy to integrate a PR with good test coverage. Closing.

**Comment by etiennestuder** [comment]
The location of the directory in which the credentials file is stored is configurable in version 1.0.7. If you specify a location relative to the project on which you apply the credentials plugin, you will be able to achieve the behaviour you are requesting.
